import { ProductTable } from "@/components/products/ProductTable";
import { useState } from "react";
import type { Product } from "@/types/product";

export function Products() {
  const [selectedProducts, setSelectedProducts] = useState<number[]>([]);
  const [products] = useState<Product[]>([
    {
      id: 1,
      name: "Product 1",
      description: "Description for Product 1",
      price: 100,
      stock: 50,
      sku: "SKU001",
      discountPrice: 90,
      currency: "USD",
      tax: 10,
      category: "Category 1",
      tags: ["tag1", "tag2"],
      images: ["/placeholder.svg"],
      rating: 4.5,
      reviews: [],
      specifications: {},
      variants: []
    },
    {
      id: 2,
      name: "Product 2",
      description: "Description for Product 2",
      price: 200,
      stock: 30,
      sku: "SKU002",
      discountPrice: 180,
      currency: "USD",
      tax: 15,
      category: "Category 2",
      tags: ["tag3", "tag4"],
      images: ["/placeholder.svg"],
      rating: 4.0,
      reviews: [],
      specifications: {},
      variants: []
    },
    {
      id: 3,
      name: "Product 3",
      description: "Description for Product 3",
      price: 150,
      stock: 20,
      sku: "SKU003",
      discountPrice: 140,
      currency: "USD",
      tax: 12,
      category: "Category 1",
      tags: ["tag1", "tag5"],
      images: ["/placeholder.svg"],
      rating: 4.2,
      reviews: [],
      specifications: {},
      variants: []
    },
    {
      id: 4,
      name: "Product 4",
      description: "Description for Product 4",
      price: 250,
      stock: 10,
      sku: "SKU004",
      discountPrice: 230,
      currency: "USD",
      tax: 20,
      category: "Category 3",
      tags: ["tag6", "tag7"],
      images: ["/placeholder.svg"],
      rating: 4.8,
      reviews: [],
      specifications: {},
      variants: []
    },
    {
      id: 5,
      name: "Product 5",
      description: "Description for Product 5",
      price: 300,
      stock: 5,
      sku: "SKU005",
      discountPrice: 280,
      currency: "USD",
      tax: 25,
      category: "Category 2",
      tags: ["tag8", "tag9"],
      images: ["/placeholder.svg"],
      rating: 4.6,
      reviews: [],
      specifications: {},
      variants: []
    },
    {
      id: 6,
      name: "Product 6",
      description: "Description for Product 6",
      price: 120,
      stock: 40,
      sku: "SKU006",
      discountPrice: 110,
      currency: "USD",
      tax: 8,
      category: "Category 1",
      tags: ["tag1", "tag10"],
      images: ["/placeholder.svg"],
      rating: 4.1,
      reviews: [],
      specifications: {},
      variants: []
    },
    {
      id: 7,
      name: "Product 7",
      description: "Description for Product 7",
      price: 180,
      stock: 25,
      sku: "SKU007",
      discountPrice: 160,
      currency: "USD",
      tax: 18,
      category: "Category 3",
      tags: ["tag11", "tag12"],
      images: ["/placeholder.svg"],
      rating: 4.3,
      reviews: [],
      specifications: {},
      variants: []
    },
    {
      id: 8,
      name: "Product 8",
      description: "Description for Product 8",
      price: 220,
      stock: 15,
      sku: "SKU008",
      discountPrice: 200,
      currency: "USD",
      tax: 22,
      category: "Category 2",
      tags: ["tag13", "tag14"],
      images: ["/placeholder.svg"],
      rating: 4.7,
      reviews: [],
      specifications: {},
      variants: []
    },
    {
      id: 9,
      name: "Product 9",
      description: "Description for Product 9",
      price: 90,
      stock: 60,
      sku: "SKU009",
      discountPrice: 80,
      currency: "USD",
      tax: 5,
      category: "Category 1",
      tags: ["tag15", "tag16"],
      images: ["/placeholder.svg"],
      rating: 4.0,
      reviews: [],
      specifications: {},
      variants: []
    },
    {
      id: 10,
      name: "Product 10",
      description: "Description for Product 10",
      price: 130,
      stock: 35,
      sku: "SKU010",
      discountPrice: 120,
      currency: "USD",
      tax: 10,
      category: "Category 3",
      tags: ["tag17", "tag18"],
      images: ["/placeholder.svg"],
      rating: 4.4,
      reviews: [],
      specifications: {},
      variants: []
    },
    {
      id: 11,
      name: "Product 11",
      description: "Description for Product 11",
      price: 160,
      stock: 45,
      sku: "SKU011",
      discountPrice: 150,
      currency: "USD",
      tax: 12,
      category: "Category 2",
      tags: ["tag19", "tag20"],
      images: ["/placeholder.svg"],
      rating: 4.5,
      reviews: [],
      specifications: {},
      variants: []
    },
    {
      id: 12,
      name: "Product 12",
      description: "Description for Product 12",
      price: 210,
      stock: 20,
      sku: "SKU012",
      discountPrice: 200,
      currency: "USD",
      tax: 15,
      category: "Category 1",
      tags: ["tag21", "tag22"],
      images: ["/placeholder.svg"],
      rating: 4.2,
      reviews: [],
      specifications: {},
      variants: []
    },
    {
      id: 13,
      name: "Product 13",
      description: "Description for Product 13",
      price: 240,
      stock: 10,
      sku: "SKU013",
      discountPrice: 230,
      currency: "USD",
      tax: 20,
      category: "Category 3",
      tags: ["tag23", "tag24"],
      images: ["/placeholder.svg"],
      rating: 4.8,
      reviews: [],
      specifications: {},
      variants: []
    },
    {
      id: 14,
      name: "Product 14",
      description: "Description for Product 14",
      price: 170,
      stock: 30,
      sku: "SKU014",
      discountPrice: 160,
      currency: "USD",
      tax: 18,
      category: "Category 2",
      tags: ["tag25", "tag26"],
      images: ["/placeholder.svg"],
      rating: 4.3,
      reviews: [],
      specifications: {},
      variants: []
    },
    {
      id: 15,
      name: "Product 15",
      description: "Description for Product 15",
      price: 190,
      stock: 25,
      sku: "SKU015",
      discountPrice: 180,
      currency: "USD",
      tax: 15,
      category: "Category 1",
      tags: ["tag27", "tag28"],
      images: ["/placeholder.svg"],
      rating: 4.6,
      reviews: [],
      specifications: {},
      variants: []
    },
    {
      id: 16,
      name: "Product 16",
      description: "Description for Product 16",
      price: 110,
      stock: 50,
      sku: "SKU016",
      discountPrice: 100,
      currency: "USD",
      tax: 8,
      category: "Category 3",
      tags: ["tag29", "tag30"],
      images: ["/placeholder.svg"],
      rating: 4.1,
      reviews: [],
      specifications: {},
      variants: []
    },
    {
      id: 17,
      name: "Product 17",
      description: "Description for Product 17",
      price: 130,
      stock: 40,
      sku: "SKU017",
      discountPrice: 120,
      currency: "USD",
      tax: 10,
      category: "Category 2",
      tags: ["tag31", "tag32"],
      images: ["/placeholder.svg"],
      rating: 4.4,
      reviews: [],
      specifications: {},
      variants: []
    },
    {
      id: 18,
      name: "Product 18",
      description: "Description for Product 18",
      price: 150,
      stock: 30,
      sku: "SKU018",
      discountPrice: 140,
      currency: "USD",
      tax: 12,
      category: "Category 1",
      tags: ["tag33", "tag34"],
      images: ["/placeholder.svg"],
      rating: 4.2,
      reviews: [],
      specifications: {},
      variants: []
    },
    {
      id: 19,
      name: "Product 19",
      description: "Description for Product 19",
      price: 170,
      stock: 20,
      sku: "SKU019",
      discountPrice: 160,
      currency: "USD",
      tax: 15,
      category: "Category 3",
      tags: ["tag35", "tag36"],
      images: ["/placeholder.svg"],
      rating: 4.5,
      reviews: [],
      specifications: {},
      variants: []
    },
    {
      id: 20,
      name: "Product 20",
      description: "Description for Product 20",
      price: 190,
      stock: 10,
      sku: "SKU020",
      discountPrice: 180,
      currency: "USD",
      tax: 20,
      category: "Category 2",
      tags: ["tag37", "tag38"],
      images: ["/placeholder.svg"],
      rating: 4.3,
      reviews: [],
      specifications: {},
      variants: []
    },
  ]);

  const handleSelectProduct = (productId: number) => {
    setSelectedProducts(prev => 
      prev.includes(productId) 
        ? prev.filter(id => id !== productId)
        : [...prev, productId]
    );
  };

  const handleSelectAll = () => {
    setSelectedProducts(prev => 
      prev.length === products.length ? [] : products.map(p => p.id)
    );
  };

  return (
    <div className="space-y-4">
      <ProductTable
        products={products}
        selectedProducts={selectedProducts}
        onSelectProduct={handleSelectProduct}
        onSelectAll={handleSelectAll}
      />
    </div>
  );
}
