export default {
  code: 'font-mono text-sm',
  heading: {
    h1: 'text-4xl font-bold',
    h2: 'text-3xl font-bold',
    h3: 'text-2xl font-bold',
    h4: 'text-xl font-bold',
    h5: 'text-lg font-bold',
  },
  image: 'max-w-full h-auto',
  link: 'text-blue-500 underline',
  list: {
    ul: 'list-disc list-inside',
    ulDepth: ['list-disc list-inside', 'list-disc list-inside ml-4'],
    ol: 'list-decimal list-inside',
    olDepth: ['list-decimal list-inside', 'list-decimal list-inside ml-4'],
    checklist: 'list-none list-inside',
    listitem: 'list-inside',
    listitemChecked: 'list-inside line-through',
    listitemUnchecked: 'list-inside',
    nested: {
      list: 'list-none list-inside ml-4',
      listitem: 'list-none list-inside ml-4',
    },
  },
  ltr: 'ltr',
  paragraph: 'mb-4',
  placeholder: 'text-gray-500',
  quote: 'border-l-4 border-gray-300 pl-4 italic',
  rtl: 'rtl',
  text: {
    bold: 'font-bold',
    code: 'font-mono text-sm bg-gray-100 p-1 rounded',
    hashtag: 'text-blue-500',
    italic: 'italic',
    overflowed: 'truncate',
    strikethrough: 'line-through',
    underline: 'underline',
    underlineStrikethrough: 'underline line-through',
  }
};